name: Build Cross-Platform Apps

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ccc_attendance_with_UI.py'
      - '.github/workflows/main.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pyinstaller qrcode[pil]

      - name: Install UPX
        run: choco install upx -y

      - name: Build Windows Executable
        run: >
          pyinstaller --onefile --windowed --noconfirm --clean
          --name "CCC Attendance"
          --exclude-module tkinter.test
          --exclude-module unittest
          --exclude-module pydoc
          ccc_attendance_with_UI.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CCC_Attendance_Windows_x64
          path: "dist/CCC Attendance.exe"

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pyinstaller qrcode[pil]

      - name: Install UPX
        run: brew install upx || true

      - name: Build macOS App
        run: >
          pyinstaller --onefile --windowed --strip --noconfirm --clean
          --name "CCC Attendance"
          --exclude-module tkinter.test
          --exclude-module unittest
          --exclude-module pydoc
          ccc_attendance_with_UI.py

      - name: Generate DMG
        run: hdiutil create -volname "CCC Attendance" -srcfolder "dist/CCC Attendance.app" -ov -format UDZO "dist/CCC Attendance.dmg"

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CCC_Attendance_macOS
          path: "dist/CCC Attendance.dmg"
